
services:
  imeego:
    container_name: flask_app
    build: .
    ports:
      - "6001:6001"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001/health"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - rabbitmq
      - crm-db

  worker:
    build: .
    container_name: email_worker
    command: ["python", "-u", "app/email_worker.py"]
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - imeego
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f email_worker || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app

  crm-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: crm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq

volumes:
  dbdata: